### ISSUE TITLE
Update elastic4s to 5.2.x

### ISSUE THREAD

**Issue by sergiohgz** [Tecsisa/lightQL#11]
Hi,

We are expecting an update to elastic4s 5.2.x because, in this version, Elasticsearch added support for sorting with keyword fields (as they removed by 5.x).
Are you planning to make this update?
In case you cannot and you want, we can contribute with it.

Thank you so much

**Comment by sergiohgz** [comment]
I was investigating and the current lightql-materializer will not compile because some elements from **elastic4s-core** were extracted into another layer. This layer is composed by two subprojects, **elastic4s-tcp** and **elastic4s-http**.
As the documentation says, this change comes from Elasticsearch Java API, which has added a new **HTTP Client** based in **Java REST Client**. At least for now, it has less functionality than the original Java Client. I was looking **Lightql** implementation more depth and I think it could be easy to create materializer for both clients, separating into two different projects (to remove transitive dependencies between e4s http and tcp implementations) (if necessary).

**Source:** [elastic4s documentation](https://github.com/sksamuel/elastic4s#introduction)

**Comment by juanjovazquez** [comment]
@sergiohgz Would be just enough to shift to `elastic4s-tcp` for the time being at least?

**Comment by sergiohgz** [comment]
It is not enough to shift to that specific package, **elastic4s** removed the direct support to **QueryBuilder**, so the materializer provided does not compile.
It is defined as `Materializer[QueryBuilder]`, where **QueryBuilder** is a piece of Java Elasticsearch library.
Talking with **elastic4s** author, he told me to shift to the **QueryDefinitions** from **elastic4s** or use a JSON created from **QueryBuilder**.

**Source:** [elatic4s gitter channel](https://gitter.im/sksamuel/elastic4s?at=58b7469c21d548df2c797a77)
