### ISSUE TITLE
Malformed view in documentation

### ISSUE THREAD

**Issue by sergiohgz** [Tecsisa/lightQL#16]
Hi,

Moving through the docs I advice that something should not appear.
![sthshouldnotbethere](https://cloud.githubusercontent.com/assets/14012309/25394652/ed79c80c-29de-11e7-9067-ae9867ff21a0.png)
Above the header of the section appear sth about layout and position. Looking the way the site is created (with sbt-microsites), that specific file is copied from outside the MD working directory, and the copy of the file contains the same content and a new header config (that is why your config is showing on view and not renderized).
I will make a PR with the correction.

Regards

**Comment by juanjovazquez** [comment]
Thanks for catching this!
