### ISSUE TITLE
Provide mechanism for searching inner and nested objects

### ISSUE THREAD

**Issue by sergiohgz** [Tecsisa/lightQL#8]
Hi,

we are trying to create queries against fields with object type (also called inner object) and those searches don't generate result when they should.
We had a look in the **materializer** package and found that if the field which we want to query contains a dot, that query is transformed in a nestedQuery. 
The nestedQuery introduces a special field in the _JSON_ called **path** which represents the path where the object should be indexed. Nested fields are the way _ES_ index arrays of objects (as describe the [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html)).
We think that is a good approach modifying the current checking for nestedFields for something that checks for other syntax (sth as having a dot inside the field and brackets around the value) and use dots for inner objects search.

What do you think about?

Thank you so much

**Comment by juanjovazquez** [comment]
@sergiohgz Please, could you provide some code to show the proposed syntax for both nested and object fields support?

**Comment by sergiohgz** [comment]
@juanjovazquez Following the example in tests, we thought in this:
- Object --> ```"stats.rate.stars = 5"```
- Nested --> ```"stats.rate.stars = [5]"```
But this can be confusing due to value will be materialized in a list of values, so I think doing sth with operator or name field for nested field like this other:
- Nested --> ```"[stats.rate.stars] = 5"```

**Comment by juanjovazquez** [comment]
@sergiohgz What do you think about sticking to the old syntax with dots for object fields but replacing the dots with arrows for nested ones, e.g.: `stats->rate->stars = 5`?

**Comment by sergiohgz** [comment]
LGTM

**Comment by sergiohgz** [comment]
If you like, I can make a PR with changes and some good examples.

**Comment by juanjovazquez** [comment]
Great!. PRs are welcome!.
